apiVersion: v1
kind: Service
metadata:
  namespace: validation-webhook
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-cert
  name: webhook
  labels:
    app: webhook
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: webhook